server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vno_organization
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-enough}

  
management:
  endpoints:
    web:
      exposure:
        include: health,info,openapi,swagger-ui  # thêm openapi + swagger-ui
  info:
    env:
      enabled: true  # enable /actuator/info
  endpoint:
    health:
      show-details: always