server:
  port: 8761

spring:
  application:
    name: service-discovery


management:
  zipkin:
    tracing:
      enabled: false
      
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:eureka-secret@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.netflix.eureka: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
