server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: "optional:configserver:http://config:config123@localhost:8888"
  cloud:
    gateway:
      routes:
        # Route cho API auth
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/auth/$\{segment}

        # Route CHO SWAGGER: lấy /v3/api-docs từ auth-service
        - id: auth-openapi
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs
  security:
    user:
      name: admin
      password: 123456
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
 
# application.yml của api-gateway
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Authentication
        url: /api-docs/auth
      - name: User Service
        url: /api-docs/user

management:
  tracing:
    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-secret@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
