server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: "optional:configserver:http://config:config123@localhost:8888"
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/api/notes/**
  security:
      user:
        name: admin
        password: 123456
 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: user-service
        url: /users/v3/api-docs
      - name: note-service
        url: /notes/v3/api-docs
      - name: tag-service
        url: /tags/v3/api-docs
      - name: organization-service
        url: /organizations/v3/api-docs
      - name: notification-service
        url: /notifications/v3/api-docs


management:
  tracing:
    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-secret@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
