server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:http://config:config123@localhost:8888"
  cloud:
    gateway:
      routes:
        # Auth Service OpenAPI
        - id: openapi-auth
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        # User Service OpenAPI
        - id: openapi-user
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user
          filters:
            - RewritePath=/v3/api-docs/user, /v3/api-docs

        # Organization Service OpenAPI
        - id: openapi-org
          uri: lb://organization-service
          predicates:
            - Path=/v3/api-docs/org
          filters:
            - RewritePath=/v3/api-docs/org, /v3/api-docs
  security:
    user:
      name: admin
      password: 123456
    basic:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
 
# application.yml của api-gateway
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: VNO Aggregated API
        url: /v3/api-docs/aggregated
      - name: Auth Service
        url: /v3/api-docs/auth
      - name: User Service
        url: /v3/api-docs/user
      - name: Org Service
        url: /v3/api-docs/org
    config-url: /v3/api-docs/aggregated

management:
  tracing:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-secret@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
