version: '3.8'

services:
  service-discovery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - vno-network

networks:
  vno-network:
    driver: bridge